#!/usr/bin/env ansible-playbook
# ./all.yml --ask-become-pass
---
- name: check
  hosts: all
  tasks:
    - name: shell command
      shell: echo "hello" > hello.txt

    - name: hello
      shell: echo "world" >> hello.txt